//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CL_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCH_SCHOOL
    {
        public int esc_id { get; set; }
        public string esc_name { get; set; }
        public string esc_address { get; set; }
    }
}
